name: Docker

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: tempushubregistry.azurecr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: /empedobot


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY }}
            username: TempusHubRegistry
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - working-directory: ./src/Empedo.Discord
          run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}${{ secrets.IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}${{ secrets.IMAGE_NAME }}:${{ github.sha }}
